-- Add 30 Elite Templates Migration V2 (Corrected Syntax)

-- Updating business-card-custom
DO $$
DECLARE
  v_variants JSONB := '[]'::jsonb;
  v_mappings JSONB := '{}'::jsonb;
  v_config JSONB;
BEGIN
  v_config := '{"mappings": {}, "fields": []}'::jsonb;
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 31', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/bc/31/front.svg', '/templates/bc/31/back.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 0::text || '_0'], '{"name":{"x":50,"y":48,"fontSize":32,"fontWeight":"bold","align":"center"},"title":{"x":50,"y":58,"fontSize":16,"fontWeight":"normal","align":"center"},"phone":{"x":50,"y":75,"fontSize":12,"fontWeight":"normal","align":"center"},"email":{"x":50,"y":82,"fontSize":12,"fontWeight":"normal","align":"center"},"logo":{"x":45,"y":20,"w":10,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 32', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/bc/32/front.svg', '/templates/bc/32/back.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 1::text || '_0'], '{"name":{"x":10,"y":45,"fontSize":36,"fontWeight":"bold","align":"left"},"title":{"x":10,"y":55,"fontSize":18,"fontWeight":"normal","align":"left"},"phone":{"x":10,"y":78,"fontSize":12,"fontWeight":"normal","align":"left"},"email":{"x":10,"y":85,"fontSize":12,"fontWeight":"normal","align":"left"},"logo":{"x":80,"y":15,"w":12,"h":12}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 33', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/bc/33/front.svg', '/templates/bc/33/back.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 2::text || '_0'], '{"name":{"x":40,"y":45,"fontSize":32,"fontWeight":"bold","align":"left"},"title":{"x":40,"y":55,"fontSize":16,"fontWeight":"normal","align":"left"},"phone":{"x":40,"y":75,"fontSize":12,"fontWeight":"normal","align":"left"},"email":{"x":40,"y":82,"fontSize":12,"fontWeight":"normal","align":"left"},"logo":{"x":5,"y":40,"w":20,"h":20}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 34', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/bc/34/front.svg', '/templates/bc/34/back.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 3::text || '_0'], '{"name":{"x":50,"y":48,"fontSize":32,"fontWeight":"bold","align":"center"},"title":{"x":50,"y":58,"fontSize":16,"fontWeight":"normal","align":"center"},"phone":{"x":50,"y":75,"fontSize":12,"fontWeight":"normal","align":"center"},"email":{"x":50,"y":82,"fontSize":12,"fontWeight":"normal","align":"center"},"logo":{"x":45,"y":20,"w":10,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 35', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/bc/35/front.svg', '/templates/bc/35/back.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 4::text || '_0'], '{"name":{"x":50,"y":48,"fontSize":32,"fontWeight":"bold","align":"center"},"title":{"x":50,"y":58,"fontSize":16,"fontWeight":"normal","align":"center"},"phone":{"x":50,"y":75,"fontSize":12,"fontWeight":"normal","align":"center"},"email":{"x":50,"y":82,"fontSize":12,"fontWeight":"normal","align":"center"},"logo":{"x":45,"y":20,"w":10,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 36', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/bc/36/front.svg', '/templates/bc/36/back.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 5::text || '_0'], '{"name":{"x":50,"y":48,"fontSize":32,"fontWeight":"bold","align":"center"},"title":{"x":50,"y":58,"fontSize":16,"fontWeight":"normal","align":"center"},"phone":{"x":50,"y":75,"fontSize":12,"fontWeight":"normal","align":"center"},"email":{"x":50,"y":82,"fontSize":12,"fontWeight":"normal","align":"center"},"logo":{"x":45,"y":20,"w":10,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 37', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/bc/37/front.svg', '/templates/bc/37/back.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 6::text || '_0'], '{"name":{"x":10,"y":45,"fontSize":36,"fontWeight":"bold","align":"left"},"title":{"x":10,"y":55,"fontSize":18,"fontWeight":"normal","align":"left"},"phone":{"x":10,"y":78,"fontSize":12,"fontWeight":"normal","align":"left"},"email":{"x":10,"y":85,"fontSize":12,"fontWeight":"normal","align":"left"},"logo":{"x":80,"y":15,"w":12,"h":12}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 38', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/bc/38/front.svg', '/templates/bc/38/back.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 7::text || '_0'], '{"name":{"x":40,"y":45,"fontSize":32,"fontWeight":"bold","align":"left"},"title":{"x":40,"y":55,"fontSize":16,"fontWeight":"normal","align":"left"},"phone":{"x":40,"y":75,"fontSize":12,"fontWeight":"normal","align":"left"},"email":{"x":40,"y":82,"fontSize":12,"fontWeight":"normal","align":"left"},"logo":{"x":5,"y":40,"w":20,"h":20}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 39', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/bc/39/front.svg', '/templates/bc/39/back.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 8::text || '_0'], '{"name":{"x":50,"y":48,"fontSize":32,"fontWeight":"bold","align":"center"},"title":{"x":50,"y":58,"fontSize":16,"fontWeight":"normal","align":"center"},"phone":{"x":50,"y":75,"fontSize":12,"fontWeight":"normal","align":"center"},"email":{"x":50,"y":82,"fontSize":12,"fontWeight":"normal","align":"center"},"logo":{"x":45,"y":20,"w":10,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 40', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/bc/40/front.svg', '/templates/bc/40/back.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 9::text || '_0'], '{"name":{"x":50,"y":48,"fontSize":32,"fontWeight":"bold","align":"center"},"title":{"x":50,"y":58,"fontSize":16,"fontWeight":"normal","align":"center"},"phone":{"x":50,"y":75,"fontSize":12,"fontWeight":"normal","align":"center"},"email":{"x":50,"y":82,"fontSize":12,"fontWeight":"normal","align":"center"},"logo":{"x":45,"y":20,"w":10,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 41', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/bc/41/front.svg', '/templates/bc/41/back.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 10::text || '_0'], '{"name":{"x":50,"y":48,"fontSize":32,"fontWeight":"bold","align":"center"},"title":{"x":50,"y":58,"fontSize":16,"fontWeight":"normal","align":"center"},"phone":{"x":50,"y":75,"fontSize":12,"fontWeight":"normal","align":"center"},"email":{"x":50,"y":82,"fontSize":12,"fontWeight":"normal","align":"center"},"logo":{"x":45,"y":20,"w":10,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 42', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/bc/42/front.svg', '/templates/bc/42/back.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 11::text || '_0'], '{"name":{"x":10,"y":45,"fontSize":36,"fontWeight":"bold","align":"left"},"title":{"x":10,"y":55,"fontSize":18,"fontWeight":"normal","align":"left"},"phone":{"x":10,"y":78,"fontSize":12,"fontWeight":"normal","align":"left"},"email":{"x":10,"y":85,"fontSize":12,"fontWeight":"normal","align":"left"},"logo":{"x":80,"y":15,"w":12,"h":12}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 43', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/bc/43/front.svg', '/templates/bc/43/back.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 12::text || '_0'], '{"name":{"x":40,"y":45,"fontSize":32,"fontWeight":"bold","align":"left"},"title":{"x":40,"y":55,"fontSize":16,"fontWeight":"normal","align":"left"},"phone":{"x":40,"y":75,"fontSize":12,"fontWeight":"normal","align":"left"},"email":{"x":40,"y":82,"fontSize":12,"fontWeight":"normal","align":"left"},"logo":{"x":5,"y":40,"w":20,"h":20}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 44', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/bc/44/front.svg', '/templates/bc/44/back.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 13::text || '_0'], '{"name":{"x":50,"y":48,"fontSize":32,"fontWeight":"bold","align":"center"},"title":{"x":50,"y":58,"fontSize":16,"fontWeight":"normal","align":"center"},"phone":{"x":50,"y":75,"fontSize":12,"fontWeight":"normal","align":"center"},"email":{"x":50,"y":82,"fontSize":12,"fontWeight":"normal","align":"center"},"logo":{"x":45,"y":20,"w":10,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 45', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/bc/45/front.svg', '/templates/bc/45/back.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 14::text || '_0'], '{"name":{"x":50,"y":48,"fontSize":32,"fontWeight":"bold","align":"center"},"title":{"x":50,"y":58,"fontSize":16,"fontWeight":"normal","align":"center"},"phone":{"x":50,"y":75,"fontSize":12,"fontWeight":"normal","align":"center"},"email":{"x":50,"y":82,"fontSize":12,"fontWeight":"normal","align":"center"},"logo":{"x":45,"y":20,"w":10,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 46', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/bc/46/front.svg', '/templates/bc/46/back.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 15::text || '_0'], '{"name":{"x":50,"y":48,"fontSize":32,"fontWeight":"bold","align":"center"},"title":{"x":50,"y":58,"fontSize":16,"fontWeight":"normal","align":"center"},"phone":{"x":50,"y":75,"fontSize":12,"fontWeight":"normal","align":"center"},"email":{"x":50,"y":82,"fontSize":12,"fontWeight":"normal","align":"center"},"logo":{"x":45,"y":20,"w":10,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 47', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/bc/47/front.svg', '/templates/bc/47/back.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 16::text || '_0'], '{"name":{"x":10,"y":45,"fontSize":36,"fontWeight":"bold","align":"left"},"title":{"x":10,"y":55,"fontSize":18,"fontWeight":"normal","align":"left"},"phone":{"x":10,"y":78,"fontSize":12,"fontWeight":"normal","align":"left"},"email":{"x":10,"y":85,"fontSize":12,"fontWeight":"normal","align":"left"},"logo":{"x":80,"y":15,"w":12,"h":12}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 48', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/bc/48/front.svg', '/templates/bc/48/back.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 17::text || '_0'], '{"name":{"x":40,"y":45,"fontSize":32,"fontWeight":"bold","align":"left"},"title":{"x":40,"y":55,"fontSize":16,"fontWeight":"normal","align":"left"},"phone":{"x":40,"y":75,"fontSize":12,"fontWeight":"normal","align":"left"},"email":{"x":40,"y":82,"fontSize":12,"fontWeight":"normal","align":"left"},"logo":{"x":5,"y":40,"w":20,"h":20}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 49', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/bc/49/front.svg', '/templates/bc/49/back.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 18::text || '_0'], '{"name":{"x":50,"y":48,"fontSize":32,"fontWeight":"bold","align":"center"},"title":{"x":50,"y":58,"fontSize":16,"fontWeight":"normal","align":"center"},"phone":{"x":50,"y":75,"fontSize":12,"fontWeight":"normal","align":"center"},"email":{"x":50,"y":82,"fontSize":12,"fontWeight":"normal","align":"center"},"logo":{"x":45,"y":20,"w":10,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 50', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/bc/50/front.svg', '/templates/bc/50/back.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 19::text || '_0'], '{"name":{"x":50,"y":48,"fontSize":32,"fontWeight":"bold","align":"center"},"title":{"x":50,"y":58,"fontSize":16,"fontWeight":"normal","align":"center"},"phone":{"x":50,"y":75,"fontSize":12,"fontWeight":"normal","align":"center"},"email":{"x":50,"y":82,"fontSize":12,"fontWeight":"normal","align":"center"},"logo":{"x":45,"y":20,"w":10,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 51', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/bc/51/front.svg', '/templates/bc/51/back.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 20::text || '_0'], '{"name":{"x":50,"y":48,"fontSize":32,"fontWeight":"bold","align":"center"},"title":{"x":50,"y":58,"fontSize":16,"fontWeight":"normal","align":"center"},"phone":{"x":50,"y":75,"fontSize":12,"fontWeight":"normal","align":"center"},"email":{"x":50,"y":82,"fontSize":12,"fontWeight":"normal","align":"center"},"logo":{"x":45,"y":20,"w":10,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 52', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/bc/52/front.svg', '/templates/bc/52/back.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 21::text || '_0'], '{"name":{"x":10,"y":45,"fontSize":36,"fontWeight":"bold","align":"left"},"title":{"x":10,"y":55,"fontSize":18,"fontWeight":"normal","align":"left"},"phone":{"x":10,"y":78,"fontSize":12,"fontWeight":"normal","align":"left"},"email":{"x":10,"y":85,"fontSize":12,"fontWeight":"normal","align":"left"},"logo":{"x":80,"y":15,"w":12,"h":12}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 53', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/bc/53/front.svg', '/templates/bc/53/back.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 22::text || '_0'], '{"name":{"x":40,"y":45,"fontSize":32,"fontWeight":"bold","align":"left"},"title":{"x":40,"y":55,"fontSize":16,"fontWeight":"normal","align":"left"},"phone":{"x":40,"y":75,"fontSize":12,"fontWeight":"normal","align":"left"},"email":{"x":40,"y":82,"fontSize":12,"fontWeight":"normal","align":"left"},"logo":{"x":5,"y":40,"w":20,"h":20}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 54', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/bc/54/front.svg', '/templates/bc/54/back.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 23::text || '_0'], '{"name":{"x":50,"y":48,"fontSize":32,"fontWeight":"bold","align":"center"},"title":{"x":50,"y":58,"fontSize":16,"fontWeight":"normal","align":"center"},"phone":{"x":50,"y":75,"fontSize":12,"fontWeight":"normal","align":"center"},"email":{"x":50,"y":82,"fontSize":12,"fontWeight":"normal","align":"center"},"logo":{"x":45,"y":20,"w":10,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 55', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/bc/55/front.svg', '/templates/bc/55/back.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 24::text || '_0'], '{"name":{"x":50,"y":48,"fontSize":32,"fontWeight":"bold","align":"center"},"title":{"x":50,"y":58,"fontSize":16,"fontWeight":"normal","align":"center"},"phone":{"x":50,"y":75,"fontSize":12,"fontWeight":"normal","align":"center"},"email":{"x":50,"y":82,"fontSize":12,"fontWeight":"normal","align":"center"},"logo":{"x":45,"y":20,"w":10,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 56', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/bc/56/front.svg', '/templates/bc/56/back.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 25::text || '_0'], '{"name":{"x":50,"y":48,"fontSize":32,"fontWeight":"bold","align":"center"},"title":{"x":50,"y":58,"fontSize":16,"fontWeight":"normal","align":"center"},"phone":{"x":50,"y":75,"fontSize":12,"fontWeight":"normal","align":"center"},"email":{"x":50,"y":82,"fontSize":12,"fontWeight":"normal","align":"center"},"logo":{"x":45,"y":20,"w":10,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 57', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/bc/57/front.svg', '/templates/bc/57/back.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 26::text || '_0'], '{"name":{"x":10,"y":45,"fontSize":36,"fontWeight":"bold","align":"left"},"title":{"x":10,"y":55,"fontSize":18,"fontWeight":"normal","align":"left"},"phone":{"x":10,"y":78,"fontSize":12,"fontWeight":"normal","align":"left"},"email":{"x":10,"y":85,"fontSize":12,"fontWeight":"normal","align":"left"},"logo":{"x":80,"y":15,"w":12,"h":12}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 58', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/bc/58/front.svg', '/templates/bc/58/back.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 27::text || '_0'], '{"name":{"x":40,"y":45,"fontSize":32,"fontWeight":"bold","align":"left"},"title":{"x":40,"y":55,"fontSize":16,"fontWeight":"normal","align":"left"},"phone":{"x":40,"y":75,"fontSize":12,"fontWeight":"normal","align":"left"},"email":{"x":40,"y":82,"fontSize":12,"fontWeight":"normal","align":"left"},"logo":{"x":5,"y":40,"w":20,"h":20}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 59', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/bc/59/front.svg', '/templates/bc/59/back.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 28::text || '_0'], '{"name":{"x":50,"y":48,"fontSize":32,"fontWeight":"bold","align":"center"},"title":{"x":50,"y":58,"fontSize":16,"fontWeight":"normal","align":"center"},"phone":{"x":50,"y":75,"fontSize":12,"fontWeight":"normal","align":"center"},"email":{"x":50,"y":82,"fontSize":12,"fontWeight":"normal","align":"center"},"logo":{"x":45,"y":20,"w":10,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 60', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/bc/60/front.svg', '/templates/bc/60/back.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 29::text || '_0'], '{"name":{"x":50,"y":48,"fontSize":32,"fontWeight":"bold","align":"center"},"title":{"x":50,"y":58,"fontSize":16,"fontWeight":"normal","align":"center"},"phone":{"x":50,"y":75,"fontSize":12,"fontWeight":"normal","align":"center"},"email":{"x":50,"y":82,"fontSize":12,"fontWeight":"normal","align":"center"},"logo":{"x":45,"y":20,"w":10,"h":10}}'::jsonb);
  -- Preservation logic
  SELECT design_config INTO v_config FROM products WHERE slug = 'business-card-custom';
  IF v_config IS NULL THEN v_config := '{"fields": []}'::jsonb; END IF;
  IF v_config->'fields' IS NULL OR jsonb_array_length(v_config->'fields') = 0 THEN
    v_config := jsonb_set(v_config, '{fields}', '[{"id": "name", "label": "Full Name", "type": "text"}, {"id": "title", "label": "Job Title", "type": "text"}, {"id": "phone", "label": "Phone", "type": "text"}, {"id": "email", "label": "Email", "type": "text"}]'::jsonb);
  END IF;
  UPDATE products SET color_variants = v_variants, design_config = v_config, design_mode = 'template_form' WHERE slug = 'business-card-custom';
END $$;

-- Updating id-card-custom
DO $$
DECLARE
  v_variants JSONB := '[]'::jsonb;
  v_mappings JSONB := '{}'::jsonb;
  v_config JSONB;
BEGIN
  v_config := '{"mappings": {}, "fields": []}'::jsonb;
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 11', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/id/11/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 0::text || '_0'], '{"name":{"x":50,"y":65,"fontSize":28,"fontWeight":"bold","align":"center"},"id_no":{"x":50,"y":72,"fontSize":14,"fontWeight":"normal","align":"center"},"designation":{"x":50,"y":78,"fontSize":14,"fontWeight":"bold","align":"center"},"logo":{"x":40,"y":10,"w":20,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 12', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/id/12/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 1::text || '_0'], '{"name":{"x":50,"y":65,"fontSize":28,"fontWeight":"bold","align":"center"},"id_no":{"x":50,"y":72,"fontSize":14,"fontWeight":"normal","align":"center"},"designation":{"x":50,"y":78,"fontSize":14,"fontWeight":"bold","align":"center"},"logo":{"x":40,"y":10,"w":20,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 13', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/id/13/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 2::text || '_0'], '{"name":{"x":50,"y":65,"fontSize":28,"fontWeight":"bold","align":"center"},"id_no":{"x":50,"y":72,"fontSize":14,"fontWeight":"normal","align":"center"},"designation":{"x":50,"y":78,"fontSize":14,"fontWeight":"bold","align":"center"},"logo":{"x":40,"y":10,"w":20,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 14', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/id/14/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 3::text || '_0'], '{"name":{"x":50,"y":65,"fontSize":28,"fontWeight":"bold","align":"center"},"id_no":{"x":50,"y":72,"fontSize":14,"fontWeight":"normal","align":"center"},"designation":{"x":50,"y":78,"fontSize":14,"fontWeight":"bold","align":"center"},"logo":{"x":40,"y":10,"w":20,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 15', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/id/15/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 4::text || '_0'], '{"name":{"x":50,"y":65,"fontSize":28,"fontWeight":"bold","align":"center"},"id_no":{"x":50,"y":72,"fontSize":14,"fontWeight":"normal","align":"center"},"designation":{"x":50,"y":78,"fontSize":14,"fontWeight":"bold","align":"center"},"logo":{"x":40,"y":10,"w":20,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 16', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/id/16/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 5::text || '_0'], '{"name":{"x":50,"y":65,"fontSize":28,"fontWeight":"bold","align":"center"},"id_no":{"x":50,"y":72,"fontSize":14,"fontWeight":"normal","align":"center"},"designation":{"x":50,"y":78,"fontSize":14,"fontWeight":"bold","align":"center"},"logo":{"x":40,"y":10,"w":20,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 17', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/id/17/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 6::text || '_0'], '{"name":{"x":50,"y":65,"fontSize":28,"fontWeight":"bold","align":"center"},"id_no":{"x":50,"y":72,"fontSize":14,"fontWeight":"normal","align":"center"},"designation":{"x":50,"y":78,"fontSize":14,"fontWeight":"bold","align":"center"},"logo":{"x":40,"y":10,"w":20,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 18', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/id/18/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 7::text || '_0'], '{"name":{"x":50,"y":65,"fontSize":28,"fontWeight":"bold","align":"center"},"id_no":{"x":50,"y":72,"fontSize":14,"fontWeight":"normal","align":"center"},"designation":{"x":50,"y":78,"fontSize":14,"fontWeight":"bold","align":"center"},"logo":{"x":40,"y":10,"w":20,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 19', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/id/19/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 8::text || '_0'], '{"name":{"x":50,"y":65,"fontSize":28,"fontWeight":"bold","align":"center"},"id_no":{"x":50,"y":72,"fontSize":14,"fontWeight":"normal","align":"center"},"designation":{"x":50,"y":78,"fontSize":14,"fontWeight":"bold","align":"center"},"logo":{"x":40,"y":10,"w":20,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 20', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/id/20/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 9::text || '_0'], '{"name":{"x":50,"y":65,"fontSize":28,"fontWeight":"bold","align":"center"},"id_no":{"x":50,"y":72,"fontSize":14,"fontWeight":"normal","align":"center"},"designation":{"x":50,"y":78,"fontSize":14,"fontWeight":"bold","align":"center"},"logo":{"x":40,"y":10,"w":20,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 21', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/id/21/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 10::text || '_0'], '{"name":{"x":50,"y":65,"fontSize":28,"fontWeight":"bold","align":"center"},"id_no":{"x":50,"y":72,"fontSize":14,"fontWeight":"normal","align":"center"},"designation":{"x":50,"y":78,"fontSize":14,"fontWeight":"bold","align":"center"},"logo":{"x":40,"y":10,"w":20,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 22', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/id/22/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 11::text || '_0'], '{"name":{"x":50,"y":65,"fontSize":28,"fontWeight":"bold","align":"center"},"id_no":{"x":50,"y":72,"fontSize":14,"fontWeight":"normal","align":"center"},"designation":{"x":50,"y":78,"fontSize":14,"fontWeight":"bold","align":"center"},"logo":{"x":40,"y":10,"w":20,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 23', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/id/23/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 12::text || '_0'], '{"name":{"x":50,"y":65,"fontSize":28,"fontWeight":"bold","align":"center"},"id_no":{"x":50,"y":72,"fontSize":14,"fontWeight":"normal","align":"center"},"designation":{"x":50,"y":78,"fontSize":14,"fontWeight":"bold","align":"center"},"logo":{"x":40,"y":10,"w":20,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 24', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/id/24/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 13::text || '_0'], '{"name":{"x":50,"y":65,"fontSize":28,"fontWeight":"bold","align":"center"},"id_no":{"x":50,"y":72,"fontSize":14,"fontWeight":"normal","align":"center"},"designation":{"x":50,"y":78,"fontSize":14,"fontWeight":"bold","align":"center"},"logo":{"x":40,"y":10,"w":20,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 25', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/id/25/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 14::text || '_0'], '{"name":{"x":50,"y":65,"fontSize":28,"fontWeight":"bold","align":"center"},"id_no":{"x":50,"y":72,"fontSize":14,"fontWeight":"normal","align":"center"},"designation":{"x":50,"y":78,"fontSize":14,"fontWeight":"bold","align":"center"},"logo":{"x":40,"y":10,"w":20,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 26', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/id/26/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 15::text || '_0'], '{"name":{"x":50,"y":65,"fontSize":28,"fontWeight":"bold","align":"center"},"id_no":{"x":50,"y":72,"fontSize":14,"fontWeight":"normal","align":"center"},"designation":{"x":50,"y":78,"fontSize":14,"fontWeight":"bold","align":"center"},"logo":{"x":40,"y":10,"w":20,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 27', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/id/27/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 16::text || '_0'], '{"name":{"x":50,"y":65,"fontSize":28,"fontWeight":"bold","align":"center"},"id_no":{"x":50,"y":72,"fontSize":14,"fontWeight":"normal","align":"center"},"designation":{"x":50,"y":78,"fontSize":14,"fontWeight":"bold","align":"center"},"logo":{"x":40,"y":10,"w":20,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 28', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/id/28/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 17::text || '_0'], '{"name":{"x":50,"y":65,"fontSize":28,"fontWeight":"bold","align":"center"},"id_no":{"x":50,"y":72,"fontSize":14,"fontWeight":"normal","align":"center"},"designation":{"x":50,"y":78,"fontSize":14,"fontWeight":"bold","align":"center"},"logo":{"x":40,"y":10,"w":20,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 29', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/id/29/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 18::text || '_0'], '{"name":{"x":50,"y":65,"fontSize":28,"fontWeight":"bold","align":"center"},"id_no":{"x":50,"y":72,"fontSize":14,"fontWeight":"normal","align":"center"},"designation":{"x":50,"y":78,"fontSize":14,"fontWeight":"bold","align":"center"},"logo":{"x":40,"y":10,"w":20,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 30', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/id/30/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 19::text || '_0'], '{"name":{"x":50,"y":65,"fontSize":28,"fontWeight":"bold","align":"center"},"id_no":{"x":50,"y":72,"fontSize":14,"fontWeight":"normal","align":"center"},"designation":{"x":50,"y":78,"fontSize":14,"fontWeight":"bold","align":"center"},"logo":{"x":40,"y":10,"w":20,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 31', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/id/31/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 20::text || '_0'], '{"name":{"x":50,"y":65,"fontSize":28,"fontWeight":"bold","align":"center"},"id_no":{"x":50,"y":72,"fontSize":14,"fontWeight":"normal","align":"center"},"designation":{"x":50,"y":78,"fontSize":14,"fontWeight":"bold","align":"center"},"logo":{"x":40,"y":10,"w":20,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 32', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/id/32/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 21::text || '_0'], '{"name":{"x":50,"y":65,"fontSize":28,"fontWeight":"bold","align":"center"},"id_no":{"x":50,"y":72,"fontSize":14,"fontWeight":"normal","align":"center"},"designation":{"x":50,"y":78,"fontSize":14,"fontWeight":"bold","align":"center"},"logo":{"x":40,"y":10,"w":20,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 33', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/id/33/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 22::text || '_0'], '{"name":{"x":50,"y":65,"fontSize":28,"fontWeight":"bold","align":"center"},"id_no":{"x":50,"y":72,"fontSize":14,"fontWeight":"normal","align":"center"},"designation":{"x":50,"y":78,"fontSize":14,"fontWeight":"bold","align":"center"},"logo":{"x":40,"y":10,"w":20,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 34', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/id/34/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 23::text || '_0'], '{"name":{"x":50,"y":65,"fontSize":28,"fontWeight":"bold","align":"center"},"id_no":{"x":50,"y":72,"fontSize":14,"fontWeight":"normal","align":"center"},"designation":{"x":50,"y":78,"fontSize":14,"fontWeight":"bold","align":"center"},"logo":{"x":40,"y":10,"w":20,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 35', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/id/35/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 24::text || '_0'], '{"name":{"x":50,"y":65,"fontSize":28,"fontWeight":"bold","align":"center"},"id_no":{"x":50,"y":72,"fontSize":14,"fontWeight":"normal","align":"center"},"designation":{"x":50,"y":78,"fontSize":14,"fontWeight":"bold","align":"center"},"logo":{"x":40,"y":10,"w":20,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 36', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/id/36/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 25::text || '_0'], '{"name":{"x":50,"y":65,"fontSize":28,"fontWeight":"bold","align":"center"},"id_no":{"x":50,"y":72,"fontSize":14,"fontWeight":"normal","align":"center"},"designation":{"x":50,"y":78,"fontSize":14,"fontWeight":"bold","align":"center"},"logo":{"x":40,"y":10,"w":20,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 37', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/id/37/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 26::text || '_0'], '{"name":{"x":50,"y":65,"fontSize":28,"fontWeight":"bold","align":"center"},"id_no":{"x":50,"y":72,"fontSize":14,"fontWeight":"normal","align":"center"},"designation":{"x":50,"y":78,"fontSize":14,"fontWeight":"bold","align":"center"},"logo":{"x":40,"y":10,"w":20,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 38', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/id/38/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 27::text || '_0'], '{"name":{"x":50,"y":65,"fontSize":28,"fontWeight":"bold","align":"center"},"id_no":{"x":50,"y":72,"fontSize":14,"fontWeight":"normal","align":"center"},"designation":{"x":50,"y":78,"fontSize":14,"fontWeight":"bold","align":"center"},"logo":{"x":40,"y":10,"w":20,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 39', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/id/39/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 28::text || '_0'], '{"name":{"x":50,"y":65,"fontSize":28,"fontWeight":"bold","align":"center"},"id_no":{"x":50,"y":72,"fontSize":14,"fontWeight":"normal","align":"center"},"designation":{"x":50,"y":78,"fontSize":14,"fontWeight":"bold","align":"center"},"logo":{"x":40,"y":10,"w":20,"h":10}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 40', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/id/40/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 29::text || '_0'], '{"name":{"x":50,"y":65,"fontSize":28,"fontWeight":"bold","align":"center"},"id_no":{"x":50,"y":72,"fontSize":14,"fontWeight":"normal","align":"center"},"designation":{"x":50,"y":78,"fontSize":14,"fontWeight":"bold","align":"center"},"logo":{"x":40,"y":10,"w":20,"h":10}}'::jsonb);
  -- Preservation logic
  SELECT design_config INTO v_config FROM products WHERE slug = 'id-card-custom';
  IF v_config IS NULL THEN v_config := '{"fields": []}'::jsonb; END IF;
  IF v_config->'fields' IS NULL OR jsonb_array_length(v_config->'fields') = 0 THEN
  END IF;
  UPDATE products SET color_variants = v_variants, design_config = v_config, design_mode = 'template_form' WHERE slug = 'id-card-custom';
END $$;

-- Updating wedding-card-custom
DO $$
DECLARE
  v_variants JSONB := '[]'::jsonb;
  v_mappings JSONB := '{}'::jsonb;
  v_config JSONB;
BEGIN
  v_config := '{"mappings": {}, "fields": []}'::jsonb;
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 11', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/wc/11/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 0::text || '_0'], '{"groom":{"x":50,"y":35,"fontSize":48,"fontWeight":"bold","align":"center"},"bride":{"x":50,"y":50,"fontSize":48,"fontWeight":"bold","align":"center"},"date":{"x":50,"y":65,"fontSize":20,"fontWeight":"normal","align":"center"},"venue":{"x":50,"y":80,"fontSize":16,"fontWeight":"normal","align":"center"}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 12', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/wc/12/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 1::text || '_0'], '{"groom":{"x":50,"y":35,"fontSize":48,"fontWeight":"bold","align":"center"},"bride":{"x":50,"y":50,"fontSize":48,"fontWeight":"bold","align":"center"},"date":{"x":50,"y":65,"fontSize":20,"fontWeight":"normal","align":"center"},"venue":{"x":50,"y":80,"fontSize":16,"fontWeight":"normal","align":"center"}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 13', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/wc/13/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 2::text || '_0'], '{"groom":{"x":50,"y":35,"fontSize":48,"fontWeight":"bold","align":"center"},"bride":{"x":50,"y":50,"fontSize":48,"fontWeight":"bold","align":"center"},"date":{"x":50,"y":65,"fontSize":20,"fontWeight":"normal","align":"center"},"venue":{"x":50,"y":80,"fontSize":16,"fontWeight":"normal","align":"center"}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 14', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/wc/14/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 3::text || '_0'], '{"groom":{"x":50,"y":35,"fontSize":48,"fontWeight":"bold","align":"center"},"bride":{"x":50,"y":50,"fontSize":48,"fontWeight":"bold","align":"center"},"date":{"x":50,"y":65,"fontSize":20,"fontWeight":"normal","align":"center"},"venue":{"x":50,"y":80,"fontSize":16,"fontWeight":"normal","align":"center"}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 15', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/wc/15/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 4::text || '_0'], '{"groom":{"x":50,"y":35,"fontSize":48,"fontWeight":"bold","align":"center"},"bride":{"x":50,"y":50,"fontSize":48,"fontWeight":"bold","align":"center"},"date":{"x":50,"y":65,"fontSize":20,"fontWeight":"normal","align":"center"},"venue":{"x":50,"y":80,"fontSize":16,"fontWeight":"normal","align":"center"}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 16', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/wc/16/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 5::text || '_0'], '{"groom":{"x":50,"y":35,"fontSize":48,"fontWeight":"bold","align":"center"},"bride":{"x":50,"y":50,"fontSize":48,"fontWeight":"bold","align":"center"},"date":{"x":50,"y":65,"fontSize":20,"fontWeight":"normal","align":"center"},"venue":{"x":50,"y":80,"fontSize":16,"fontWeight":"normal","align":"center"}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 17', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/wc/17/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 6::text || '_0'], '{"groom":{"x":50,"y":35,"fontSize":48,"fontWeight":"bold","align":"center"},"bride":{"x":50,"y":50,"fontSize":48,"fontWeight":"bold","align":"center"},"date":{"x":50,"y":65,"fontSize":20,"fontWeight":"normal","align":"center"},"venue":{"x":50,"y":80,"fontSize":16,"fontWeight":"normal","align":"center"}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 18', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/wc/18/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 7::text || '_0'], '{"groom":{"x":50,"y":35,"fontSize":48,"fontWeight":"bold","align":"center"},"bride":{"x":50,"y":50,"fontSize":48,"fontWeight":"bold","align":"center"},"date":{"x":50,"y":65,"fontSize":20,"fontWeight":"normal","align":"center"},"venue":{"x":50,"y":80,"fontSize":16,"fontWeight":"normal","align":"center"}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 19', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/wc/19/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 8::text || '_0'], '{"groom":{"x":50,"y":35,"fontSize":48,"fontWeight":"bold","align":"center"},"bride":{"x":50,"y":50,"fontSize":48,"fontWeight":"bold","align":"center"},"date":{"x":50,"y":65,"fontSize":20,"fontWeight":"normal","align":"center"},"venue":{"x":50,"y":80,"fontSize":16,"fontWeight":"normal","align":"center"}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 20', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/wc/20/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 9::text || '_0'], '{"groom":{"x":50,"y":35,"fontSize":48,"fontWeight":"bold","align":"center"},"bride":{"x":50,"y":50,"fontSize":48,"fontWeight":"bold","align":"center"},"date":{"x":50,"y":65,"fontSize":20,"fontWeight":"normal","align":"center"},"venue":{"x":50,"y":80,"fontSize":16,"fontWeight":"normal","align":"center"}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 21', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/wc/21/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 10::text || '_0'], '{"groom":{"x":50,"y":35,"fontSize":48,"fontWeight":"bold","align":"center"},"bride":{"x":50,"y":50,"fontSize":48,"fontWeight":"bold","align":"center"},"date":{"x":50,"y":65,"fontSize":20,"fontWeight":"normal","align":"center"},"venue":{"x":50,"y":80,"fontSize":16,"fontWeight":"normal","align":"center"}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 22', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/wc/22/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 11::text || '_0'], '{"groom":{"x":50,"y":35,"fontSize":48,"fontWeight":"bold","align":"center"},"bride":{"x":50,"y":50,"fontSize":48,"fontWeight":"bold","align":"center"},"date":{"x":50,"y":65,"fontSize":20,"fontWeight":"normal","align":"center"},"venue":{"x":50,"y":80,"fontSize":16,"fontWeight":"normal","align":"center"}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 23', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/wc/23/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 12::text || '_0'], '{"groom":{"x":50,"y":35,"fontSize":48,"fontWeight":"bold","align":"center"},"bride":{"x":50,"y":50,"fontSize":48,"fontWeight":"bold","align":"center"},"date":{"x":50,"y":65,"fontSize":20,"fontWeight":"normal","align":"center"},"venue":{"x":50,"y":80,"fontSize":16,"fontWeight":"normal","align":"center"}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 24', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/wc/24/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 13::text || '_0'], '{"groom":{"x":50,"y":35,"fontSize":48,"fontWeight":"bold","align":"center"},"bride":{"x":50,"y":50,"fontSize":48,"fontWeight":"bold","align":"center"},"date":{"x":50,"y":65,"fontSize":20,"fontWeight":"normal","align":"center"},"venue":{"x":50,"y":80,"fontSize":16,"fontWeight":"normal","align":"center"}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 25', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/wc/25/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 14::text || '_0'], '{"groom":{"x":50,"y":35,"fontSize":48,"fontWeight":"bold","align":"center"},"bride":{"x":50,"y":50,"fontSize":48,"fontWeight":"bold","align":"center"},"date":{"x":50,"y":65,"fontSize":20,"fontWeight":"normal","align":"center"},"venue":{"x":50,"y":80,"fontSize":16,"fontWeight":"normal","align":"center"}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 26', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/wc/26/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 15::text || '_0'], '{"groom":{"x":50,"y":35,"fontSize":48,"fontWeight":"bold","align":"center"},"bride":{"x":50,"y":50,"fontSize":48,"fontWeight":"bold","align":"center"},"date":{"x":50,"y":65,"fontSize":20,"fontWeight":"normal","align":"center"},"venue":{"x":50,"y":80,"fontSize":16,"fontWeight":"normal","align":"center"}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 27', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/wc/27/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 16::text || '_0'], '{"groom":{"x":50,"y":35,"fontSize":48,"fontWeight":"bold","align":"center"},"bride":{"x":50,"y":50,"fontSize":48,"fontWeight":"bold","align":"center"},"date":{"x":50,"y":65,"fontSize":20,"fontWeight":"normal","align":"center"},"venue":{"x":50,"y":80,"fontSize":16,"fontWeight":"normal","align":"center"}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 28', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/wc/28/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 17::text || '_0'], '{"groom":{"x":50,"y":35,"fontSize":48,"fontWeight":"bold","align":"center"},"bride":{"x":50,"y":50,"fontSize":48,"fontWeight":"bold","align":"center"},"date":{"x":50,"y":65,"fontSize":20,"fontWeight":"normal","align":"center"},"venue":{"x":50,"y":80,"fontSize":16,"fontWeight":"normal","align":"center"}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 29', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/wc/29/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 18::text || '_0'], '{"groom":{"x":50,"y":35,"fontSize":48,"fontWeight":"bold","align":"center"},"bride":{"x":50,"y":50,"fontSize":48,"fontWeight":"bold","align":"center"},"date":{"x":50,"y":65,"fontSize":20,"fontWeight":"normal","align":"center"},"venue":{"x":50,"y":80,"fontSize":16,"fontWeight":"normal","align":"center"}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 30', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/wc/30/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 19::text || '_0'], '{"groom":{"x":50,"y":35,"fontSize":48,"fontWeight":"bold","align":"center"},"bride":{"x":50,"y":50,"fontSize":48,"fontWeight":"bold","align":"center"},"date":{"x":50,"y":65,"fontSize":20,"fontWeight":"normal","align":"center"},"venue":{"x":50,"y":80,"fontSize":16,"fontWeight":"normal","align":"center"}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 31', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/wc/31/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 20::text || '_0'], '{"groom":{"x":50,"y":35,"fontSize":48,"fontWeight":"bold","align":"center"},"bride":{"x":50,"y":50,"fontSize":48,"fontWeight":"bold","align":"center"},"date":{"x":50,"y":65,"fontSize":20,"fontWeight":"normal","align":"center"},"venue":{"x":50,"y":80,"fontSize":16,"fontWeight":"normal","align":"center"}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 32', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/wc/32/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 21::text || '_0'], '{"groom":{"x":50,"y":35,"fontSize":48,"fontWeight":"bold","align":"center"},"bride":{"x":50,"y":50,"fontSize":48,"fontWeight":"bold","align":"center"},"date":{"x":50,"y":65,"fontSize":20,"fontWeight":"normal","align":"center"},"venue":{"x":50,"y":80,"fontSize":16,"fontWeight":"normal","align":"center"}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 33', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/wc/33/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 22::text || '_0'], '{"groom":{"x":50,"y":35,"fontSize":48,"fontWeight":"bold","align":"center"},"bride":{"x":50,"y":50,"fontSize":48,"fontWeight":"bold","align":"center"},"date":{"x":50,"y":65,"fontSize":20,"fontWeight":"normal","align":"center"},"venue":{"x":50,"y":80,"fontSize":16,"fontWeight":"normal","align":"center"}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 34', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/wc/34/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 23::text || '_0'], '{"groom":{"x":50,"y":35,"fontSize":48,"fontWeight":"bold","align":"center"},"bride":{"x":50,"y":50,"fontSize":48,"fontWeight":"bold","align":"center"},"date":{"x":50,"y":65,"fontSize":20,"fontWeight":"normal","align":"center"},"venue":{"x":50,"y":80,"fontSize":16,"fontWeight":"normal","align":"center"}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 35', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/wc/35/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 24::text || '_0'], '{"groom":{"x":50,"y":35,"fontSize":48,"fontWeight":"bold","align":"center"},"bride":{"x":50,"y":50,"fontSize":48,"fontWeight":"bold","align":"center"},"date":{"x":50,"y":65,"fontSize":20,"fontWeight":"normal","align":"center"},"venue":{"x":50,"y":80,"fontSize":16,"fontWeight":"normal","align":"center"}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 36', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/wc/36/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 25::text || '_0'], '{"groom":{"x":50,"y":35,"fontSize":48,"fontWeight":"bold","align":"center"},"bride":{"x":50,"y":50,"fontSize":48,"fontWeight":"bold","align":"center"},"date":{"x":50,"y":65,"fontSize":20,"fontWeight":"normal","align":"center"},"venue":{"x":50,"y":80,"fontSize":16,"fontWeight":"normal","align":"center"}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 37', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/wc/37/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 26::text || '_0'], '{"groom":{"x":50,"y":35,"fontSize":48,"fontWeight":"bold","align":"center"},"bride":{"x":50,"y":50,"fontSize":48,"fontWeight":"bold","align":"center"},"date":{"x":50,"y":65,"fontSize":20,"fontWeight":"normal","align":"center"},"venue":{"x":50,"y":80,"fontSize":16,"fontWeight":"normal","align":"center"}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 38', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/wc/38/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 27::text || '_0'], '{"groom":{"x":50,"y":35,"fontSize":48,"fontWeight":"bold","align":"center"},"bride":{"x":50,"y":50,"fontSize":48,"fontWeight":"bold","align":"center"},"date":{"x":50,"y":65,"fontSize":20,"fontWeight":"normal","align":"center"},"venue":{"x":50,"y":80,"fontSize":16,"fontWeight":"normal","align":"center"}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 39', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/wc/39/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 28::text || '_0'], '{"groom":{"x":50,"y":35,"fontSize":48,"fontWeight":"bold","align":"center"},"bride":{"x":50,"y":50,"fontSize":48,"fontWeight":"bold","align":"center"},"date":{"x":50,"y":65,"fontSize":20,"fontWeight":"normal","align":"center"},"venue":{"x":50,"y":80,"fontSize":16,"fontWeight":"normal","align":"center"}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 40', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/wc/40/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 29::text || '_0'], '{"groom":{"x":50,"y":35,"fontSize":48,"fontWeight":"bold","align":"center"},"bride":{"x":50,"y":50,"fontSize":48,"fontWeight":"bold","align":"center"},"date":{"x":50,"y":65,"fontSize":20,"fontWeight":"normal","align":"center"},"venue":{"x":50,"y":80,"fontSize":16,"fontWeight":"normal","align":"center"}}'::jsonb);
  -- Preservation logic
  SELECT design_config INTO v_config FROM products WHERE slug = 'wedding-card-custom';
  IF v_config IS NULL THEN v_config := '{"fields": []}'::jsonb; END IF;
  IF v_config->'fields' IS NULL OR jsonb_array_length(v_config->'fields') = 0 THEN
  END IF;
  UPDATE products SET color_variants = v_variants, design_config = v_config, design_mode = 'template_form' WHERE slug = 'wedding-card-custom';
END $$;

-- Updating letter-head-custom
DO $$
DECLARE
  v_variants JSONB := '[]'::jsonb;
  v_mappings JSONB := '{}'::jsonb;
  v_config JSONB;
BEGIN
  v_config := '{"mappings": {}, "fields": []}'::jsonb;
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 11', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/lh/11/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 0::text || '_0'], '{"company":{"x":50,"y":10,"fontSize":24,"fontWeight":"bold","align":"center"},"address":{"x":50,"y":92,"fontSize":10,"fontWeight":"normal","align":"center"},"phone":{"x":20,"y":92,"fontSize":10,"fontWeight":"normal","align":"left"},"email":{"x":80,"y":92,"fontSize":10,"fontWeight":"normal","align":"right"},"logo":{"x":10,"y":8,"w":10,"h":8}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 12', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/lh/12/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 1::text || '_0'], '{"company":{"x":50,"y":10,"fontSize":24,"fontWeight":"bold","align":"center"},"address":{"x":50,"y":92,"fontSize":10,"fontWeight":"normal","align":"center"},"phone":{"x":20,"y":92,"fontSize":10,"fontWeight":"normal","align":"left"},"email":{"x":80,"y":92,"fontSize":10,"fontWeight":"normal","align":"right"},"logo":{"x":10,"y":8,"w":10,"h":8}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 13', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/lh/13/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 2::text || '_0'], '{"company":{"x":50,"y":10,"fontSize":24,"fontWeight":"bold","align":"center"},"address":{"x":50,"y":92,"fontSize":10,"fontWeight":"normal","align":"center"},"phone":{"x":20,"y":92,"fontSize":10,"fontWeight":"normal","align":"left"},"email":{"x":80,"y":92,"fontSize":10,"fontWeight":"normal","align":"right"},"logo":{"x":10,"y":8,"w":10,"h":8}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 14', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/lh/14/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 3::text || '_0'], '{"company":{"x":50,"y":10,"fontSize":24,"fontWeight":"bold","align":"center"},"address":{"x":50,"y":92,"fontSize":10,"fontWeight":"normal","align":"center"},"phone":{"x":20,"y":92,"fontSize":10,"fontWeight":"normal","align":"left"},"email":{"x":80,"y":92,"fontSize":10,"fontWeight":"normal","align":"right"},"logo":{"x":10,"y":8,"w":10,"h":8}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 15', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/lh/15/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 4::text || '_0'], '{"company":{"x":50,"y":10,"fontSize":24,"fontWeight":"bold","align":"center"},"address":{"x":50,"y":92,"fontSize":10,"fontWeight":"normal","align":"center"},"phone":{"x":20,"y":92,"fontSize":10,"fontWeight":"normal","align":"left"},"email":{"x":80,"y":92,"fontSize":10,"fontWeight":"normal","align":"right"},"logo":{"x":10,"y":8,"w":10,"h":8}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 16', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/lh/16/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 5::text || '_0'], '{"company":{"x":50,"y":10,"fontSize":24,"fontWeight":"bold","align":"center"},"address":{"x":50,"y":92,"fontSize":10,"fontWeight":"normal","align":"center"},"phone":{"x":20,"y":92,"fontSize":10,"fontWeight":"normal","align":"left"},"email":{"x":80,"y":92,"fontSize":10,"fontWeight":"normal","align":"right"},"logo":{"x":10,"y":8,"w":10,"h":8}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 17', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/lh/17/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 6::text || '_0'], '{"company":{"x":50,"y":10,"fontSize":24,"fontWeight":"bold","align":"center"},"address":{"x":50,"y":92,"fontSize":10,"fontWeight":"normal","align":"center"},"phone":{"x":20,"y":92,"fontSize":10,"fontWeight":"normal","align":"left"},"email":{"x":80,"y":92,"fontSize":10,"fontWeight":"normal","align":"right"},"logo":{"x":10,"y":8,"w":10,"h":8}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 18', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/lh/18/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 7::text || '_0'], '{"company":{"x":50,"y":10,"fontSize":24,"fontWeight":"bold","align":"center"},"address":{"x":50,"y":92,"fontSize":10,"fontWeight":"normal","align":"center"},"phone":{"x":20,"y":92,"fontSize":10,"fontWeight":"normal","align":"left"},"email":{"x":80,"y":92,"fontSize":10,"fontWeight":"normal","align":"right"},"logo":{"x":10,"y":8,"w":10,"h":8}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 19', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/lh/19/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 8::text || '_0'], '{"company":{"x":50,"y":10,"fontSize":24,"fontWeight":"bold","align":"center"},"address":{"x":50,"y":92,"fontSize":10,"fontWeight":"normal","align":"center"},"phone":{"x":20,"y":92,"fontSize":10,"fontWeight":"normal","align":"left"},"email":{"x":80,"y":92,"fontSize":10,"fontWeight":"normal","align":"right"},"logo":{"x":10,"y":8,"w":10,"h":8}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 20', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/lh/20/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 9::text || '_0'], '{"company":{"x":50,"y":10,"fontSize":24,"fontWeight":"bold","align":"center"},"address":{"x":50,"y":92,"fontSize":10,"fontWeight":"normal","align":"center"},"phone":{"x":20,"y":92,"fontSize":10,"fontWeight":"normal","align":"left"},"email":{"x":80,"y":92,"fontSize":10,"fontWeight":"normal","align":"right"},"logo":{"x":10,"y":8,"w":10,"h":8}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 21', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/lh/21/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 10::text || '_0'], '{"company":{"x":50,"y":10,"fontSize":24,"fontWeight":"bold","align":"center"},"address":{"x":50,"y":92,"fontSize":10,"fontWeight":"normal","align":"center"},"phone":{"x":20,"y":92,"fontSize":10,"fontWeight":"normal","align":"left"},"email":{"x":80,"y":92,"fontSize":10,"fontWeight":"normal","align":"right"},"logo":{"x":10,"y":8,"w":10,"h":8}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 22', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/lh/22/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 11::text || '_0'], '{"company":{"x":50,"y":10,"fontSize":24,"fontWeight":"bold","align":"center"},"address":{"x":50,"y":92,"fontSize":10,"fontWeight":"normal","align":"center"},"phone":{"x":20,"y":92,"fontSize":10,"fontWeight":"normal","align":"left"},"email":{"x":80,"y":92,"fontSize":10,"fontWeight":"normal","align":"right"},"logo":{"x":10,"y":8,"w":10,"h":8}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 23', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/lh/23/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 12::text || '_0'], '{"company":{"x":50,"y":10,"fontSize":24,"fontWeight":"bold","align":"center"},"address":{"x":50,"y":92,"fontSize":10,"fontWeight":"normal","align":"center"},"phone":{"x":20,"y":92,"fontSize":10,"fontWeight":"normal","align":"left"},"email":{"x":80,"y":92,"fontSize":10,"fontWeight":"normal","align":"right"},"logo":{"x":10,"y":8,"w":10,"h":8}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 24', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/lh/24/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 13::text || '_0'], '{"company":{"x":50,"y":10,"fontSize":24,"fontWeight":"bold","align":"center"},"address":{"x":50,"y":92,"fontSize":10,"fontWeight":"normal","align":"center"},"phone":{"x":20,"y":92,"fontSize":10,"fontWeight":"normal","align":"left"},"email":{"x":80,"y":92,"fontSize":10,"fontWeight":"normal","align":"right"},"logo":{"x":10,"y":8,"w":10,"h":8}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 25', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/lh/25/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 14::text || '_0'], '{"company":{"x":50,"y":10,"fontSize":24,"fontWeight":"bold","align":"center"},"address":{"x":50,"y":92,"fontSize":10,"fontWeight":"normal","align":"center"},"phone":{"x":20,"y":92,"fontSize":10,"fontWeight":"normal","align":"left"},"email":{"x":80,"y":92,"fontSize":10,"fontWeight":"normal","align":"right"},"logo":{"x":10,"y":8,"w":10,"h":8}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 26', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/lh/26/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 15::text || '_0'], '{"company":{"x":50,"y":10,"fontSize":24,"fontWeight":"bold","align":"center"},"address":{"x":50,"y":92,"fontSize":10,"fontWeight":"normal","align":"center"},"phone":{"x":20,"y":92,"fontSize":10,"fontWeight":"normal","align":"left"},"email":{"x":80,"y":92,"fontSize":10,"fontWeight":"normal","align":"right"},"logo":{"x":10,"y":8,"w":10,"h":8}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 27', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/lh/27/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 16::text || '_0'], '{"company":{"x":50,"y":10,"fontSize":24,"fontWeight":"bold","align":"center"},"address":{"x":50,"y":92,"fontSize":10,"fontWeight":"normal","align":"center"},"phone":{"x":20,"y":92,"fontSize":10,"fontWeight":"normal","align":"left"},"email":{"x":80,"y":92,"fontSize":10,"fontWeight":"normal","align":"right"},"logo":{"x":10,"y":8,"w":10,"h":8}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 28', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/lh/28/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 17::text || '_0'], '{"company":{"x":50,"y":10,"fontSize":24,"fontWeight":"bold","align":"center"},"address":{"x":50,"y":92,"fontSize":10,"fontWeight":"normal","align":"center"},"phone":{"x":20,"y":92,"fontSize":10,"fontWeight":"normal","align":"left"},"email":{"x":80,"y":92,"fontSize":10,"fontWeight":"normal","align":"right"},"logo":{"x":10,"y":8,"w":10,"h":8}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 29', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/lh/29/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 18::text || '_0'], '{"company":{"x":50,"y":10,"fontSize":24,"fontWeight":"bold","align":"center"},"address":{"x":50,"y":92,"fontSize":10,"fontWeight":"normal","align":"center"},"phone":{"x":20,"y":92,"fontSize":10,"fontWeight":"normal","align":"left"},"email":{"x":80,"y":92,"fontSize":10,"fontWeight":"normal","align":"right"},"logo":{"x":10,"y":8,"w":10,"h":8}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 30', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/lh/30/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 19::text || '_0'], '{"company":{"x":50,"y":10,"fontSize":24,"fontWeight":"bold","align":"center"},"address":{"x":50,"y":92,"fontSize":10,"fontWeight":"normal","align":"center"},"phone":{"x":20,"y":92,"fontSize":10,"fontWeight":"normal","align":"left"},"email":{"x":80,"y":92,"fontSize":10,"fontWeight":"normal","align":"right"},"logo":{"x":10,"y":8,"w":10,"h":8}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 31', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/lh/31/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 20::text || '_0'], '{"company":{"x":50,"y":10,"fontSize":24,"fontWeight":"bold","align":"center"},"address":{"x":50,"y":92,"fontSize":10,"fontWeight":"normal","align":"center"},"phone":{"x":20,"y":92,"fontSize":10,"fontWeight":"normal","align":"left"},"email":{"x":80,"y":92,"fontSize":10,"fontWeight":"normal","align":"right"},"logo":{"x":10,"y":8,"w":10,"h":8}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 32', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/lh/32/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 21::text || '_0'], '{"company":{"x":50,"y":10,"fontSize":24,"fontWeight":"bold","align":"center"},"address":{"x":50,"y":92,"fontSize":10,"fontWeight":"normal","align":"center"},"phone":{"x":20,"y":92,"fontSize":10,"fontWeight":"normal","align":"left"},"email":{"x":80,"y":92,"fontSize":10,"fontWeight":"normal","align":"right"},"logo":{"x":10,"y":8,"w":10,"h":8}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 33', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/lh/33/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 22::text || '_0'], '{"company":{"x":50,"y":10,"fontSize":24,"fontWeight":"bold","align":"center"},"address":{"x":50,"y":92,"fontSize":10,"fontWeight":"normal","align":"center"},"phone":{"x":20,"y":92,"fontSize":10,"fontWeight":"normal","align":"left"},"email":{"x":80,"y":92,"fontSize":10,"fontWeight":"normal","align":"right"},"logo":{"x":10,"y":8,"w":10,"h":8}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 34', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/lh/34/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 23::text || '_0'], '{"company":{"x":50,"y":10,"fontSize":24,"fontWeight":"bold","align":"center"},"address":{"x":50,"y":92,"fontSize":10,"fontWeight":"normal","align":"center"},"phone":{"x":20,"y":92,"fontSize":10,"fontWeight":"normal","align":"left"},"email":{"x":80,"y":92,"fontSize":10,"fontWeight":"normal","align":"right"},"logo":{"x":10,"y":8,"w":10,"h":8}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 35', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/lh/35/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 24::text || '_0'], '{"company":{"x":50,"y":10,"fontSize":24,"fontWeight":"bold","align":"center"},"address":{"x":50,"y":92,"fontSize":10,"fontWeight":"normal","align":"center"},"phone":{"x":20,"y":92,"fontSize":10,"fontWeight":"normal","align":"left"},"email":{"x":80,"y":92,"fontSize":10,"fontWeight":"normal","align":"right"},"logo":{"x":10,"y":8,"w":10,"h":8}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 36', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/lh/36/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 25::text || '_0'], '{"company":{"x":50,"y":10,"fontSize":24,"fontWeight":"bold","align":"center"},"address":{"x":50,"y":92,"fontSize":10,"fontWeight":"normal","align":"center"},"phone":{"x":20,"y":92,"fontSize":10,"fontWeight":"normal","align":"left"},"email":{"x":80,"y":92,"fontSize":10,"fontWeight":"normal","align":"right"},"logo":{"x":10,"y":8,"w":10,"h":8}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 37', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/lh/37/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 26::text || '_0'], '{"company":{"x":50,"y":10,"fontSize":24,"fontWeight":"bold","align":"center"},"address":{"x":50,"y":92,"fontSize":10,"fontWeight":"normal","align":"center"},"phone":{"x":20,"y":92,"fontSize":10,"fontWeight":"normal","align":"left"},"email":{"x":80,"y":92,"fontSize":10,"fontWeight":"normal","align":"right"},"logo":{"x":10,"y":8,"w":10,"h":8}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 38', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/lh/38/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 27::text || '_0'], '{"company":{"x":50,"y":10,"fontSize":24,"fontWeight":"bold","align":"center"},"address":{"x":50,"y":92,"fontSize":10,"fontWeight":"normal","align":"center"},"phone":{"x":20,"y":92,"fontSize":10,"fontWeight":"normal","align":"left"},"email":{"x":80,"y":92,"fontSize":10,"fontWeight":"normal","align":"right"},"logo":{"x":10,"y":8,"w":10,"h":8}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 39', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/lh/39/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 28::text || '_0'], '{"company":{"x":50,"y":10,"fontSize":24,"fontWeight":"bold","align":"center"},"address":{"x":50,"y":92,"fontSize":10,"fontWeight":"normal","align":"center"},"phone":{"x":20,"y":92,"fontSize":10,"fontWeight":"normal","align":"left"},"email":{"x":80,"y":92,"fontSize":10,"fontWeight":"normal","align":"right"},"logo":{"x":10,"y":8,"w":10,"h":8}}'::jsonb);
  v_variants := v_variants || jsonb_build_object('name', 'Premium Elite 40', 'hex', '#000000', 'wireframe_images', jsonb_build_array('/templates/lh/40/front.svg'));
  v_config := jsonb_set(v_config, ARRAY['mappings', 29::text || '_0'], '{"company":{"x":50,"y":10,"fontSize":24,"fontWeight":"bold","align":"center"},"address":{"x":50,"y":92,"fontSize":10,"fontWeight":"normal","align":"center"},"phone":{"x":20,"y":92,"fontSize":10,"fontWeight":"normal","align":"left"},"email":{"x":80,"y":92,"fontSize":10,"fontWeight":"normal","align":"right"},"logo":{"x":10,"y":8,"w":10,"h":8}}'::jsonb);
  -- Preservation logic
  SELECT design_config INTO v_config FROM products WHERE slug = 'letter-head-custom';
  IF v_config IS NULL THEN v_config := '{"fields": []}'::jsonb; END IF;
  IF v_config->'fields' IS NULL OR jsonb_array_length(v_config->'fields') = 0 THEN
  END IF;
  UPDATE products SET color_variants = v_variants, design_config = v_config, design_mode = 'template_form' WHERE slug = 'letter-head-custom';
END $$;

